# ������汾ΪMossCGϹ�ĸĳ�����
# ����JerryZRF���޸�
# �����ǲ�������ļ�www~

#�汾��Ϣ (�������)
version: 1

#������������
max-players: 16

#������С����������ﵽ����������Ὺ�֣�
min-players: 2

#�������Runner�����ⶫ���һ����ò����˵��ǻ��ǲ���ɾ��ó����⣩
runner-max: 2

#�������������������ڵ��ڸ�����Runner�����ö�Ӧ������������ͬ��
#��L0Player=2 L0Hunter=1��������Ҵﵽ2�����ϵ�ʱ��������Ϊ1��
L0Player: 2

#�����������������
L0Runner: 1

#��һ�����������
L1Player: 6

#��һ��������������
L1Runner: 2

#�ڶ������������
L2Player: 12

#�ڶ���������������
L2Runner: 3

#���������������
L3Player: 16

#������������������
L3Runner: 4

#�Ƿ񿪾ֽ���ָ����
CompassUnlocked: true

#�Ƿ������Ϸ�Զ�����
AutoRestart: true

#������X��ƫ�ƣ�BasicΪ����ƫ�ƣ�RandomΪ���ֵ��
#ʵ��ƫ����Ϊ��Basic+Random��
#��XBasic: 10 XRandom: 20 ��ʵ��ƫ����Ϊ10+(0~20)=10~30��ȡһ�������
XBasic: 5
XRandom: 10

#������Y��ƫ�ƣ�BasicΪ����ƫ�ƣ�RandomΪ���ֵ��
#����ԭ��ͬ��
YBasic: 5
YRandom: 10

#�����߾������
#����Ŷ�ҿ��˰��췢��ԭ���߰�distanceд����distanceSquared
#Ҳ����ԭ�����Ǿ���xyz��ƽ���ͣ����޸�Ϊ�����ľ��루Ӧ��û�����ˣ�
#����������������������
WarnDistance: 50

#���ֵ���ʱʱ��
Countdown: 30

#�����߾�����Ϣ(%wd�Ǿ��������������Ǹ���%d�ǵ�ǰ���룩
WarnDistanceSafe: "%wdM ��δ��⵽����"
WarnDistanceClose: "����! �������ڿ�������ǰ���룺%dM"

#���������ƣ�ʵ����Ҳ�ͽ���ͳ�Ƶ�ʱ����ʾһ�£�
ServerName: "Example"

#��Ϸ���ƣ�ʵ����Ҳͬ���ͽ���ͳ�Ƶ�ʱ����ʾһ�£�
ServerGame: "������Ϸ"

#��ս�������ǰ׺
ObserverName: "[�Թ�]"

#׷ɱ���������ǰ׺
HunterName: "[����]"

#�������������ǰ׺
RunnerName: "[������]"

#�ȴ����������ǰ׺
WaitingName: "[�ȴ���]"

#ͳ��չʾ�Ļ�ɱ�������
DragonKiller: "������ʿ"

#ͳ��չʾ�Ļ�ɱ�����ߵ����
RunnerKiller: "�������"

#ͳ��չʾ�Ķ��κ�ʵ������˺��������
DamageOutPut: "������"

#ͳ��չʾ���ܵ��˺��������
DamageReceive: "��Ұ���"

#ͳ��չʾ�ĶԶ�������������
TeamKiller: "����ɱ��"

#ͳ��չʾ���ƶ������������
WalkMaster: "��������"

#ͳ��չʾ����Ծ�����������
JumpMaster: "�ĵϴ�ʦ"

#ͳ��չʾ������Ľ���
EndText1: "��л����"
EndText2: "Thanks for playing!"

#���ֻ�õ������
Bread: 5

#��ҵ���ĵ���ʱ
FullCountDown: 5

#˽��ǰ׺
ChatinTeam:
  - ��#��

#��Ϸ�Ѷ�
#0 ��ƽ || 1 �� || 2 ��ͨ || 3 ����
Difficult: 3

#�Ƿ������ͼ
changeMap: true